<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/v3/package.xsd" schematypenamespace="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_monitor_bringup</name>
  <version>1.0.0</version>
  <description>Launch files for robot monitor system</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>robot_monitor_mapping</exec_depend>
  <exec_depend>robot_monitor_navigation</exec_depend>
  <exec_depend>robot_monitor_ui</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
