<?xml version="1.0"?>
<package format="3">
  <name>inspection_robot_bringup</name>
  <version>0.1.0</version>
  <description>Real-robot mapping, localization, navigation and inspection bringup.</description>
  <maintainer email="zjy@example.com">zjy</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_amcl</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_behaviors</exec_depend>
  <exec_depend>nav2_smoother</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>sllidar_ros2</exec_depend>
  <exec_depend>imu_ros2_device</exec_depend>
  <exec_depend>rf2o_laser_odometry</exec_depend>
  <exec_depend>inspection_robot_hardware</exec_depend>
  <exec_depend>inspection_robot_mission</exec_depend>
  <exec_depend>inspection_robot_safety</exec_depend>
  <exec_depend>inspection_robot_dwa_controller</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
