<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mapping_bringup</name>
  <version>0.0.0</version>
  <description>Tracked robot: SLAM mapping and Nav2 autonomous navigation with RPLIDAR</description>
  <maintainer email="yy@example.com">yy</maintainer>
  <license>Apache 2.0</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>action_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2_ros</depend>
  <depend>slam_toolbox</depend>
  <depend>sllidar_ros2</depend>
  <depend>rf2o_laser_odometry</depend>
  <depend>rviz2</depend>
  <depend>nav2_map_server</depend>
  <depend>nav2_amcl</depend>
  <depend>nav2_planner</depend>
  <depend>nav2_controller</depend>
  <depend>nav2_bt_navigator</depend>
  <depend>nav2_behaviors</depend>
  <depend>nav2_smoother</depend>
  <depend>nav2_velocity_smoother</depend>
  <depend>nav2_lifecycle_manager</depend>
  <depend>nav2_bringup</depend>
  <depend>robot_monitor_interfaces</depend>
  <depend>robot_mission_utils</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
